#!/usr/bin/env python3
"""Tests of rpe2e-from-repartee on a synthetic repartee database.

Keys are generated by libsodium (as in repartee), secrets are encrypted with
AES-256-GCM in the storage::crypto::encrypt_bytes format. Run:
    python3 test_rpe2e_from_repartee.py
"""
import base64
import contextlib
import ctypes
import importlib.machinery
import importlib.util
import io
import json
import os
import sqlite3
import stat
import tempfile
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
loader = importlib.machinery.SourceFileLoader("rfr", os.path.join(HERE, "rpe2e-from-repartee"))
spec = importlib.util.spec_from_loader("rfr", loader)
rfr = importlib.util.module_from_spec(spec)
loader.exec_module(rfr)

SODIUM = rfr.load_sodium()
KEY = bytes(range(32))

SCHEMA = """
CREATE TABLE e2e_identity (id INTEGER PRIMARY KEY, pubkey BLOB, privkey BLOB, fingerprint BLOB, created_at INTEGER);
CREATE TABLE e2e_peers (fingerprint BLOB, pubkey BLOB, last_handle TEXT, last_nick TEXT, first_seen INTEGER,
    last_seen INTEGER, global_status TEXT);
CREATE TABLE e2e_outgoing_sessions (channel TEXT, sk BLOB, created_at INTEGER, pending_rotation INTEGER);
CREATE TABLE e2e_incoming_sessions (handle TEXT, channel TEXT, fingerprint BLOB, sk BLOB, status TEXT,
    created_at INTEGER, prev_sk BLOB, prev_created_at INTEGER);
CREATE TABLE e2e_channel_config (channel TEXT, enabled INTEGER, mode TEXT);
CREATE TABLE e2e_autotrust (id INTEGER PRIMARY KEY, scope TEXT, handle_pattern TEXT, created_at INTEGER);
CREATE TABLE e2e_outgoing_recipients (channel TEXT, handle TEXT, fingerprint BLOB, first_sent_at INTEGER);
"""


def encrypt(data, key=KEY):
    nonce = os.urandom(12)
    out = ctypes.create_string_buffer(len(data) + 16)
    out_len = ctypes.c_ulonglong(0)
    SODIUM.crypto_aead_aes256gcm_encrypt(
        out, ctypes.byref(out_len), data, ctypes.c_ulonglong(len(data)), None, ctypes.c_ulonglong(0), None, nonce, key
    )
    return bytes([1]) + nonce + out.raw[: out_len.value]


def keypair(seed):
    return rfr.ed25519_from_seed(SODIUM, seed)


class Fixture:
    def __init__(self, tmp):
        self.db_path = os.path.join(tmp, "messages.db")
        self.env_path = os.path.join(tmp, ".env")
        self.out_path = os.path.join(tmp, "rpe2e", "keyring.json")
        self.seed = os.urandom(32)
        self.pk, self.sk = keypair(self.seed)
        self.peer_pk, _ = keypair(os.urandom(32))
        self.old_sk, self.new_sk, self.in_old, self.in_new = (os.urandom(32) for _ in range(4))
        with open(self.env_path, "w") as fh:
            fh.write(f"REPARTEE_LOG_KEY=00\nREPARTEE_KEYRING_KEY={KEY.hex()}\n")
        db = sqlite3.connect(self.db_path)
        db.executescript(SCHEMA)
        fp = rfr.fingerprint(self.pk)
        pfp = rfr.fingerprint(self.peer_pk)
        db.execute("INSERT INTO e2e_identity VALUES (1, ?, ?, ?, 100)", (self.pk, self.seed, fp))
        db.execute("INSERT INTO e2e_peers VALUES (?, ?, 'bob@example.org', 'bob', 10, 20, 'trusted')", (pfp, self.peer_pk))
        # an older unscoped row (raw 32 B) and a newer network-scoped one (encrypted)
        db.execute("INSERT INTO e2e_outgoing_sessions VALUES ('#chan', ?, 100, 0)", (self.old_sk,))
        db.execute("INSERT INTO e2e_outgoing_sessions VALUES ('IRCnet\x1f#chan', ?, 200, 0)", (encrypt(self.new_sk),))
        db.execute("INSERT INTO e2e_incoming_sessions VALUES ('bob@example.org', '#chan', ?, ?, 'trusted', 100, NULL, NULL)",
                   (pfp, self.in_old))
        db.execute("INSERT INTO e2e_incoming_sessions VALUES ('bob@example.org', 'IRCnet\x1f#chan', ?, ?, 'trusted', 200, NULL, NULL)",
                   (pfp, encrypt(self.in_new)))
        db.execute("INSERT INTO e2e_channel_config VALUES ('#chan', 0, 'normal')")
        db.execute("INSERT INTO e2e_channel_config VALUES ('IRCnet\x1f#chan', 1, 'normal')")
        db.execute("INSERT INTO e2e_outgoing_recipients VALUES ('IRCnet\x1f#chan', 'bob@example.org', ?, 150)", (pfp,))
        db.commit()
        db.close()

    def run(self, *extra):
        return rfr.main(["--db", self.db_path, "--env", self.env_path, "--out", self.out_path, *extra])

    def keyring(self):
        with open(self.out_path) as fh:
            return json.load(fh)


class MigrationTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.f = Fixture(self.tmp.name)

    def tearDown(self):
        self.tmp.cleanup()

    def test_identity_keeps_the_fingerprint(self):
        self.assertEqual(self.f.run(), 0)
        kr = self.f.keyring()
        self.assertEqual(base64.b64decode(kr["identity"]["pk"]), self.f.pk)
        # libsodium: private key = seed || public key
        self.assertEqual(base64.b64decode(kr["identity"]["sk"]), self.f.seed + self.f.pk)
        self.assertEqual(kr["identity"]["fp"], rfr.fingerprint(self.f.pk).hex())

    def test_newest_scoped_session_wins_and_scope_is_dropped(self):
        self.f.run()
        kr = self.f.keyring()
        self.assertEqual(set(kr["outgoing"]), {"#chan"})
        self.assertEqual(base64.b64decode(kr["outgoing"]["#chan"]["sk"]), self.f.new_sk)
        self.assertEqual(set(kr["incoming"]), {"bob@example.org|#chan"})
        self.assertEqual(base64.b64decode(kr["incoming"]["bob@example.org|#chan"]["sk"]), self.f.in_new)
        self.assertEqual(kr["channels"], {"#chan": {"enabled": 1, "mode": "normal"}})
        self.assertIn("#chan|bob@example.org", kr["outgoing_recipients"])

    def test_channels_off_keeps_keys_but_waits_for_e2e_on(self):
        self.assertEqual(self.f.run("--channels-off"), 0)
        kr = self.f.keyring()
        self.assertEqual(kr["channels"], {"#chan": {"enabled": 0, "mode": "normal"}})
        self.assertIn("#chan", kr["outgoing"])
        self.assertIn("bob@example.org|#chan", kr["incoming"])

    def test_peer_layout_matches_rpe2e_pl(self):
        self.f.run()
        peer = next(iter(self.f.keyring()["peers"].values()))
        self.assertEqual(peer["status"], "trusted")
        self.assertEqual(peer["last_nick"], "bob")
        self.assertEqual(base64.b64decode(peer["pk"]), self.f.peer_pk)

    def test_file_is_private(self):
        self.f.run()
        mode = stat.S_IMODE(os.stat(self.f.out_path).st_mode)
        self.assertEqual(mode, 0o600)
        self.assertEqual(stat.S_IMODE(os.stat(os.path.dirname(self.f.out_path)).st_mode), 0o700)

    def test_existing_keyring_needs_force_and_is_backed_up(self):
        os.makedirs(os.path.dirname(self.f.out_path))
        with open(self.f.out_path, "w") as fh:
            fh.write('{"identity": "old"}')
        self.assertEqual(self.f.run(), 1)
        with open(self.f.out_path) as fh:
            self.assertIn("old", fh.read())
        self.assertEqual(self.f.run("--force"), 0)
        backups = [n for n in os.listdir(os.path.dirname(self.f.out_path)) if ".bak-" in n]
        self.assertEqual(len(backups), 1)

    def test_dry_run_writes_nothing(self):
        self.assertEqual(self.f.run("--dry-run"), 0)
        self.assertFalse(os.path.exists(self.f.out_path))

    def test_wrong_keyring_key_fails_closed(self):
        with open(self.f.env_path, "w") as fh:
            fh.write(f"REPARTEE_KEYRING_KEY={'ff' * 32}\n")
        self.assertEqual(self.f.run(), 1)
        self.assertFalse(os.path.exists(self.f.out_path))

    def test_inconsistent_identity_is_rejected(self):
        db = sqlite3.connect(self.f.db_path)
        db.execute("UPDATE e2e_identity SET pubkey = ?", (keypair(os.urandom(32))[0],))
        db.commit()
        db.close()
        self.assertEqual(self.f.run(), 1)
        self.assertFalse(os.path.exists(self.f.out_path))

    def test_tie_prefers_the_network_scoped_session(self):
        db = sqlite3.connect(self.f.db_path)
        db.execute("UPDATE e2e_outgoing_sessions SET created_at = 300")
        db.commit()
        db.close()
        self.f.run()
        self.assertEqual(base64.b64decode(self.f.keyring()["outgoing"]["#chan"]["sk"]), self.f.new_sk)

    def test_older_database_without_optional_tables(self):
        db = sqlite3.connect(self.f.db_path)
        db.execute("DROP TABLE e2e_outgoing_recipients")
        db.execute("DROP TABLE e2e_autotrust")
        db.commit()
        db.close()
        self.assertEqual(self.f.run(), 0)
        self.assertEqual(self.f.keyring()["outgoing_recipients"], {})

    def test_existing_output_directory_is_not_chmodded(self):
        os.makedirs(os.path.dirname(self.f.out_path), mode=0o755)
        os.chmod(os.path.dirname(self.f.out_path), 0o755)
        self.f.run()
        self.assertEqual(stat.S_IMODE(os.stat(os.path.dirname(self.f.out_path)).st_mode), 0o755)
        self.assertEqual(stat.S_IMODE(os.stat(self.f.out_path).st_mode), 0o600)

    def test_newest_recipient_row_wins(self):
        other_fp = rfr.fingerprint(keypair(os.urandom(32))[0])
        db = sqlite3.connect(self.f.db_path)
        # an OLDER unscoped row stored after the newer scoped one
        db.execute("INSERT INTO e2e_outgoing_recipients VALUES ('#chan', 'bob@example.org', ?, 100)", (other_fp,))
        db.commit()
        db.close()
        self.assertEqual(self.f.run(), 0)
        row = self.f.keyring()["outgoing_recipients"]["#chan|bob@example.org"]
        self.assertEqual(row["fingerprint"], rfr.fingerprint(self.f.peer_pk).hex())
        self.assertEqual(row["first_sent_at"], 150)

    def test_incoming_sessions_from_several_networks_warn(self):
        db = sqlite3.connect(self.f.db_path)
        db.execute("INSERT INTO e2e_incoming_sessions VALUES ('bob@example.org', 'OtherNet\x1f#chan', ?, ?, 'trusted', 50, NULL, NULL)",
                   (rfr.fingerprint(self.f.peer_pk), encrypt(os.urandom(32))))
        db.commit()
        db.close()
        out = io.StringIO()
        with contextlib.redirect_stdout(out):
            self.assertEqual(self.f.run(), 0)
        self.assertRegex(out.getvalue(), r"warning: .*bob@example\.org.*several networks")

    def test_session_of_unknown_peer_is_rejected(self):
        db = sqlite3.connect(self.f.db_path)
        db.execute("DELETE FROM e2e_peers")
        db.commit()
        db.close()
        self.assertEqual(self.f.run(), 1)


if __name__ == "__main__":
    unittest.main(verbosity=2)
