/*
 rpe2e-vectors.h : RPE2E wire messages produced by rpe2e.pl itself

 Generated by gen-vectors/rpe2e-vectors.pl: rpe2e.pl 0.2.2 ($RPE2E_SCRIPT),
 driven through the irssi mock in gen-vectors/lib with libsodium.
 Identities: bob = Ed25519 seed 0x42 x 32 (the rpe2e.pl side), alice =
 seed 0x41 x 32. Outgoing keys of bob: #test 0x11 x 32, #\xc5\xbcaba
 ("#żaba") 0x22 x 32, @alice@127.0.0.1 0x33 x 32. Nonces and message ids
 are random, hence the fixed copy.
*/
static const char *const vec_bob_pk_hex = "2152f8d19b791d24453242e15f2eab6cb7cffa7b6a5ed30097960e069881db12";
static const char *const vec_alice_seed_hex = "4141414141414141414141414141414141414141414141414141414141414141";
static const struct { const char *ctx, *key_hex, *plain; const char *wire[8]; } vec_wire[] = {
	{ "#test", "1111111111111111111111111111111111111111111111111111111111111111", "za\xc5""\xbc""\xc3""\xb3""\xc5""\x82""\xc4""\x87"" g\xc4""\x99""\xc5""\x9b""l\xc4""\x85"" ja\xc5""\xba""\xc5""\x84""", {
		"+RPE2E01 d0d1466184dad610 1791564129 1/1 jPGmSvxDPjj8GR4Lq51hyEiFA+0AcN3H:U7lOKlTdtYiP7xgYv4lQb8oydOftLxdXA5ee2yoDod+tSRnqvOXS0YFX",
		NULL } },
	{ "#test", "1111111111111111111111111111111111111111111111111111111111111111", "word1 word2 word3 word4 word5 word6 word7 word8 word9 word10 word11 word12 word13 word14 word15 word16 word17 word18 word19 word20 word21 word22 word23 word24 word25 word26 word27 word28 word29 word30 word31 word32 word33 word34 word35 word36 word37 word38 word39 word40 word41 word42 word43 word44 word45 word46 word47 word48 word49 word50 word51 word52 word53 word54 word55 word56 word57 word58 word59 word60 word61 word62 word63 word64 word65 word66 word67 word68 word69 word70 word71 word72 word73 word74 word75 word76 word77 word78 word79 word80", {
		"+RPE2E01 6ccbf40ba2530bc6 1791564129 1/4 1MK9Lkyo/prscU98+iwQx7e7Gpu52jl6:WO3xHV9psKx466eO4+T5bny1SOPPyWR6jhE8RVyAejKf2z5glQUI375MoIESLl29O6hg5hGPj7H8BQmFvXAJCAeYsquww/UNSKbTbW46JBce65a2MM5266yLrAP9yeUWmvjzg17vNyT1z2vOFmywpwsV3InqvbBxPFxl8zsaRB8Abjf2+bSidWgHj07p8HWQnJlWcmmSkEx5SWlPGnq+LXCrS8MlaWR5bzpRrOZNT2IozF9/PZCciays+x3B+OIrzlhGpw==",
		"+RPE2E01 6ccbf40ba2530bc6 1791564129 2/4 9Vurx19IuQPGIIR+OCAm5BKgv4rNuIvE:8c6oTD8a/e87HOdwgsIGkp3Cr8+hk6k1D6YvMydtG5Lj3quCcSqT9tUiROOOe2401XnZgfK2VtTaaw2VW8rqpQMnUuhhU/tJxNoQPPbFlf82yCT31j2yqHcOo9+l21DWVc/xwz192ZF6UZYqEPGRxbQHC38n6XhkWhdtxS5hPf4iMhAHtyfTcRWyJ5wn0XAgo4I+L2XXu7PXSRefA92REgfzhzsydOZM5nZmG4mIvEmtRtqzzhPnLLPuPzQsUJMY9dzuBA==",
		"+RPE2E01 6ccbf40ba2530bc6 1791564129 3/4 MyFruw9kkOSixZCMzm4fnxA2NTyOYtya:L+L7dl+ratFEol6wiqKKbDCfJrZ+fwUfnIY4M6jKtdVBe6KBFOk+THvuKfX2PPtm12cWnR2/Fr3q5K7enfgR8B4K/hd/SXx5sh/o3/99a+rlCqX7AmKnQqaL++xulma993VfjbguKZ+vCJruq/WXPsL05GRQamzW2vB3ws2dwaZhN+56G31TKaTMzwTrHDu1dLpL2u/UkgmJfmRAQv3y+M3mLPt0OW/QQQvPmklKWU9lUlME1k/VOSp85BdJHefd/gCpbA==",
		"+RPE2E01 6ccbf40ba2530bc6 1791564129 4/4 CGKa/bmEOlIWBrYJK3mqdFhiF7t0vaYq:RZYYDmOq8tuoyMCcxyFDPYASPDg8Ce5ayQU=",
		NULL } },
	{ "#test", "1111111111111111111111111111111111111111111111111111111111111111", "\x01""ACTION waves\x01""", {
		"+RPE2E01 6aa0a2dc06867e04 1791564129 1/1 G+Lb+zKS9jLSUP2Yh+vfiq0jojWhNsyz:wN6MWFfHzFTk3RgX+xUhZCnnbcRDD5fTOWvoAT3s",
		NULL } },
	{ "#\xc5""\xbc""aba", "2222222222222222222222222222222222222222222222222222222222222222", "hello", {
		"+RPE2E01 396b958c840d504a 1791564129 1/1 aoIDyQCW/9kDelxEU66u/tzMJCeVXlPc:Az7K12qPCo84Lrb3+OGd5+vRzSpS",
		NULL } },
	{ "@alice@127.0.0.1", "3333333333333333333333333333333333333333333333333333333333333333", "private za\xc5""\xbc""\xc3""\xb3""\xc5""\x82""\xc4""\x87"" g\xc4""\x99""\xc5""\x9b""l\xc4""\x85"" ja\xc5""\xba""\xc5""\x84""", {
		"+RPE2E01 d9ba90ce155dd169 1791564129 1/1 w5GUfiX6tb3Qn0a+2L5zjJLmuMMsNcgE:UQHEUb9qu0+Dc01errNShGbJ8t036SZSM/wEmsBpqfrgRm0pNZuTyVIcEuXfMi/oA3A=",
		NULL } },
};
static const char *const vec_keyreq = "RPEE2E KEYREQ v=1 c=#test p=IVL40Zt5HSRFMkLhXy6rbLfP-ntqXtMAl5YOBpiB2xI e=dyENFcLDQDPLOFf273NGoG4fNqqFMlJYWm3TBA06Kkk n=COJ6gbQTz82kjdu7MtoJ6g s=Aa6n-YKBtfjjkGw0OI73ic9lz0wcQuuHPrNwnNnhnwnuMH6eETdRgJZL6gwIFsm4TQB2s-QBcn8szI2cG-_qCQ";
static const char *const vec_keyreq_eph_sk_b64 = "QMlloCVR2TGGjWj/QxCSeYoAVoYdTcBw+7QWq82hOkI=";
static const char *const vec_alice_keyreq = "RPEE2E KEYREQ v=1 c=#test p=25lf4lFp0UHKubu6krqgH58uHs599MsqwFGQ83_MH50 e=OKtmS9hvd9fma92a4HkpE6lP2LM6EmACfktGwfSITGc n=ZmZmZmZmZmZmZmZmZmZmZg s=7xKpPVLBkVY1O26TiEHyCep5e1s9H0BRk0cdhI0hjqHB8yqwv6KY5joy6KMiuabKUX-H4oY9dNRMGENFt-x5CQ";
static const char *const vec_alice_eph_sk_hex = "5055555555555555555555555555555555555555555555555555555555555555";
static const char *const vec_keyrsp = "RPEE2E KEYRSP v=1 c=#test p=IVL40Zt5HSRFMkLhXy6rbLfP-ntqXtMAl5YOBpiB2xI e=NIYOGZVwjEBmWPsSgjcEmfGcUrJsVpHbRDfRkY7AUDY wn=jU2fH5QRKq2_OD_peTvbhvz5k_jomk4U w=P8W-H-RdpzgEJVE76YJkVsLVGOJHYEm0jvcSO6iIFheZ-1eOh6Gb4zQR5TAFGBdN n=RlySAUW6yvt5D97C5jZ0HQ s=SgV6ei5QHDW9dglhxuos_YAECGikECFo-32jD59HNgaMkKxg2yJiM3XvoSC3S9okqyXFbos7hb7Jr8oRAFz5Cg";
static const char *const vec_rekey = "RPEE2E REKEY v=1 c=#test p=IVL40Zt5HSRFMkLhXy6rbLfP-ntqXtMAl5YOBpiB2xI e=L57duskwHkfdxvbZVXlZWUZX6iuEbDerzv7yOLBMd3w wn=pQDvHWQfCO67wa4YTza_XFGeuE4FI6rn w=ho_MPeIqT_xrdR2MDYFUm1mX90_gTshdmcopFizUJudWqMCdxtIRE_BpjjcIL69w n=t4JUfB8ICRvhPwwz73TFww s=ghxiVyc5S4FG0dUbIYURPpi6EiKKw-RJLAf5I0VHZwtBwbTTqQfqjplTyvpUzXFD9WNz7gLaG6Z1kXWUzfgKCA";
static const char *const vec_rekey_key_hex = "4444444444444444444444444444444444444444444444444444444444444444";
