#!/usr/bin/perl
# rpe2e-vectors.pl - RPE2E messages made by rpe2e.pl itself, as C vectors
#
#   perl rpe2e-vectors.pl > ../rpe2e-vectors.h   (then add its header comment)
#
# Loads rpe2e.pl ($RPE2E_SCRIPT) with the irssi mock in gen-vectors/lib
# (needs Crypt::NaCl::Sodium and FFI::Platypus, e.g. via PERL5LIB). Fixed
# identities and keys; nonces and message ids are random, so every run gives
# other (equally valid) vectors.
use strict; use warnings;
use File::Temp qw(tempdir);
use FindBin;
use MIME::Base64 qw(encode_base64 decode_base64);
use lib "$FindBin::Bin/lib";
use Irssi;
my $DIR = tempdir(CLEANUP => 1);
$Irssi::DIR = $DIR;
my $SCRIPT = $ENV{RPE2E_SCRIPT} // die "set RPE2E_SCRIPT to a copy of rpe2e.pl\n";
{ package main; local @ARGV; do $SCRIPT or die "load $SCRIPT: $@ $!"; }
my $sodium = Crypt::NaCl::Sodium->new;
sub kp { my ($seed) = @_; my ($pk, $sk) = $sodium->sign->keypair($seed); return (main::_raw($pk), main::_raw($sk)); }
sub hex_ { unpack 'H*', $_[0] }
sub cstr { my $s = shift; $s =~ s/([\\"])/\\$1/g; $s =~ s/([^\x20-\x7e])/sprintf('\\x%02x""', ord $1)/ge; return "\"$s\""; }

my ($bob_pk, $bob_sk) = kp("\x42" x 32);
my ($alice_pk, $alice_sk) = kp("\x41" x 32);
my %K = (chan => "\x11" x 32, zaba => "\x22" x 32, dm => "\x33" x 32, rekey => "\x44" x 32);
my $ZABA = "#\xc5\xbcaba";
my $kr = main::empty_keyring();
$kr->{identity} = { pk => encode_base64($bob_pk, ''), sk => encode_base64($bob_sk, ''), fp => main::fingerprint_hex(main::fingerprint($bob_pk)), created_at => 1 };
$kr->{channels}{'#test'} = { enabled => 1, mode => 'auto-accept' };
$kr->{channels}{$ZABA} = { enabled => 1, mode => 'normal' };
$kr->{channels}{'@alice@127.0.0.1'} = { enabled => 1, mode => 'normal' };
$kr->{outgoing}{'#test'} = { sk => encode_base64($K{chan}, ''), created_at => 1, pending_rotation => 0 };
$kr->{outgoing}{$ZABA} = { sk => encode_base64($K{zaba}, ''), created_at => 1, pending_rotation => 0 };
$kr->{outgoing}{'@alice@127.0.0.1'} = { sk => encode_base64($K{dm}, ''), created_at => 1, pending_rotation => 0 };
main::save_keyring($kr) or die;

my $server = Irssi::Test::Server->new(tag => 'net', nick => 'bob');
@Irssi::SERVERS = ($server);
Irssi::Test::Item->new(server => $server, name => 'alice', type => 'QUERY', address => 'alice@127.0.0.1');
sub gate { my ($line) = @_; @{ $server->{sent} } = (); my $d = $line; Irssi::emit('server outgoing modify', $server, \$d, 1); die "not dropped: $d" if length $d; return @{ $server->{sent} }; }

print "/* generated by rpe2e.pl 0.2.2 (contrib/rpe2e) through its test mock */\n";
printf "static const char *const vec_bob_pk_hex = \"%s\";\n", hex_($bob_pk);
printf "static const char *const vec_alice_seed_hex = \"%s\";\n", hex_("\x41" x 32);
my $ZAZ = "za\xc5\xbc\xc3\xb3\xc5\x82\xc4\x87 g\xc4\x99\xc5\x9bl\xc4\x85 ja\xc5\xba\xc5\x84";
my $LONG = join(' ', map { "word$_" } 1 .. 80);
my @cases = (['#test', $K{chan}, $ZAZ, "PRIVMSG #test :$ZAZ"],
             ['#test', $K{chan}, $LONG, "PRIVMSG #test :$LONG"],
             ['#test', $K{chan}, "\x01ACTION waves\x01", "PRIVMSG #test :\x01ACTION waves\x01"],
             [$ZABA, $K{zaba}, 'hello', "PRIVMSG $ZABA :hello"],
             ['@alice@127.0.0.1', $K{dm}, "private $ZAZ", "PRIVMSG alice :private $ZAZ"]);
print "static const struct { const char *ctx, *key_hex, *plain; const char *wire[8]; } vec_wire[] = {\n";
for my $c (@cases) {
    my @w = map { s/^PRIVMSG \S+ :// ; $_ } gate($c->[3]);
    print "\t{ ", cstr($c->[0]), ", \"", hex_($c->[1]), "\", ", cstr($c->[2]), ", {\n";
    print "\t\t", cstr($_), ",\n" for @w;
    print "\t\tNULL } },\n";
}
print "};\n";

# KEYREQ built by rpe2e.pl for #test (bob -> alice); its ephemeral secret
$kr = main::load_keyring();
my $req = main::build_keyreq($kr, '#test', 'alice@127.0.0.1');
$req =~ s/^\x01|\x01$//g;
printf "static const char *const vec_keyreq = %s;\n", cstr($req);
printf "static const char *const vec_keyreq_eph_sk_b64 = \"%s\";\n", $kr->{pending}{'#test|alice@127.0.0.1'}{eph_sk};

# KEYRSP built by rpe2e.pl answering alice's KEYREQ (fixed ephemeral key)
my $eph_sk = "\x55" x 32;
my @b = unpack 'C*', $eph_sk; $b[0] &= 248; $b[31] &= 127; $b[31] |= 64; $eph_sk = pack 'C*', @b;
my $eph_pk = main::_raw($sodium->scalarmult->base($eph_sk));
my $nonce = "\x66" x 16;
my $sig = main::ed25519_sign($alice_sk, main::_sig_payload_keyreq('#test', $alice_pk, $eph_pk, $nonce));
my $areq = 'RPEE2E KEYREQ v=1 c=#test p=' . main::b64u_encode($alice_pk) . ' e=' . main::b64u_encode($eph_pk)
    . ' n=' . main::b64u_encode($nonce) . ' s=' . main::b64u_encode($sig);
printf "static const char *const vec_alice_keyreq = %s;\n", cstr($areq);
printf "static const char *const vec_alice_eph_sk_hex = \"%s\";\n", hex_($eph_sk);
$kr = main::load_keyring();
my ($rsp, $recip) = main::handle_keyreq($kr, 'alice@127.0.0.1', 'alice', $areq, 'bob@127.0.0.1');
die "no rsp" unless $rsp;
$rsp =~ s/^\x01|\x01$//g;
printf "static const char *const vec_keyrsp = %s;\n", cstr($rsp);
# REKEY to alice with a new key
my $rk = main::_build_rekey_for_peer($kr, '#test', 'alice@127.0.0.1', $alice_pk, $K{rekey});
$rk =~ s/^\x01|\x01$//g;
printf "static const char *const vec_rekey = %s;\n", cstr($rk);
printf "static const char *const vec_rekey_key_hex = \"%s\";\n", hex_($K{rekey});
