#!/bin/sh
# default-file-hashes.sh [REF [OUT]] - writes src/fe-ansi/default-files-known.h:
# the name and sha256 of every version of `startup` and themes/*.theme in
# the history of REF. erssi replaces such a file in ~/.erssi only while it
# still matches a version of that name (or the hash it recorded itself in
# ~/.erssi/default-files.sha256), so a file the user changed is never
# overwritten.
#   no REF: the history of HEAD plus the files in the working tree (run it
#           after changing a theme or `startup`, commit the header with it)
#   REF:    the history of REF plus the files in REF (the pre-push hook
#           checks the pushed commit this way)
# Only the history of REF counts - not stashes or other local refs - so
# every clone gets the same list.
set -eu
ROOT=$(git rev-parse --show-toplevel)
REF=${1:-}
OUT=${2:-$ROOT/src/fe-ansi/default-files-known.h}
cd "$ROOT"
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
list() {    # commit -> "name hash" of its startup and themes
    git ls-tree -r --name-only "$1" -- startup themes | grep -E '^(startup|themes/[^/]+\.theme)$' |
    while read -r f; do
        printf '%s %s\n' "${f##*/}" "$(git show "$1:$f" | sha256sum | cut -d' ' -f1)"
    done
}
for c in $(git log --format=%H "${REF:-HEAD}" -- startup themes); do list "$c"; done > "$tmp"
if [ -n "$REF" ]; then
    list "$REF" >> "$tmp"
else
    for f in startup themes/*.theme; do
        printf '%s %s\n' "${f##*/}" "$(sha256sum < "$f" | cut -d' ' -f1)"
    done >> "$tmp"
fi
{
    echo '/* generated by utils/default-file-hashes.sh - do not edit */'
    echo '/* every version of startup and themes/<name>.theme erssi shipped */'
    echo 'static const char *const known_default_files[][2] = {'
    sort -u "$tmp" | sed 's/^\([^ ]*\) \([0-9a-f]*\)$/\t{ "\1", "\2" },/'
    echo '	{ NULL, NULL }'
    echo '};'
} > "$OUT"
echo "$(grep -c '^	{ "' "$OUT") file versions -> $OUT"
