install_data(
  files(
    'autoop.pl',
    'autorejoin.pl',
    'botnet.pl',
    'buf.pl',
    'dns.pl',
    'kills.pl',
    'mail.pl',
    'mentions.pl',
    'mlock.pl',
    'quitmsg.pl',
    'scriptassist.pl',
    'skaner.pl',
    'tk.pl',
    'usercount.pl',
    'webjournal.pl',
  ),
  install_dir : scriptdir)
